#!/bin/sh

# temporary script to workaround stdio buffering problem
# takes a deck file and converts all cards to html
# outputs 1 per line in the form "cardid\tfront\tback"

. ./config

usage() {
	echo "usage: $0 cards.deck"
	exit 1
}

[ $# -eq 1 ] || usage

# remove extension
deck=${1%.*}

# hack to expand DELIM
IFS=$(printf $DELIM)

while read id _; do
	path="$deck"/"$id"
	front=$(md2html "$path"/front.md | tr -d '\n' |
		sed 's;src="\([^"]*\)";src="/_/'$path'/\1";g')
	back=$(md2html "$path"/back.md | tr -d '\n' |
		sed 's;src="\([^"]*\)";src="/_/'$path'/\1";g')

	extra="$path"/extra.html
	if [ -f "$extra" ]; then
		extra=$(cat "$extra" | tr -d '\n')
		front="$(echo "$front" | sed 's@==EXTRA==@'"$extra"'@g')"
		back="$(echo "$back" | sed 's@==EXTRA==@'"$extra"'@g')"
	fi

	printf "%s\t%s\t%s\n" "$id" "$front" "$back"
done < $1 \
| sed 's:\*\(\[[^*]*\)\*:<em>\1</em>:g' \
| rubify
