#!/bin/sh

. ./config

# finds and outputs the next missing id in deck ledger
[ ! -f "$1" ] && echo 0 && exit 0

sort "$1" \
| awk -F $DELIM '{
	w = length($1);
	for (i = p + 1; i < $1; i++) {
		exit
	}
} {p = $1} END {printf "%0"w"i\n", p + 1}'
