#!/bin/sh

. ./config

usage() {
	echo "usage: $0 cards.deck [cards1.deck ...]"
	exit 1
}

[ $# -lt 1 ] && usage
[ ! -f $1 ] && usage

fifo=fifo.$$
sync=sync.$$
die() {
	rm -f $fifo $sync
}
trap die EXIT INT TERM

mkfifo -m 0600 $fifo $sync

oboeru $fifo "$@" > $sync &
oboerudata $sync \
| oboeruhttp -p "$PORT" -F "$FAIL" -P "$PASS" -Q "$QUIT" -S "$SHOW" -q "$BYE" \
> $fifo &

browser "localhost:$PORT"

wait
